### ISSUE TITLE
tap事件有问题，点击下去，他会反应好几层

### ISSUE THREAD

**Issue by BlueBoyC** [BensonDu/vue-directive-touch#1]
比如说，我第一个页面的点击位置和第二个页面的点击位置重叠，当我第一个页面点击之后，他会自动帮我触发第二个页面的点击事件，然后就跳到第三个页面了

**Comment by BensonDu** [comment]
@BlueBoyC “点击穿透”问题的处理策略也有很多，原先并未考虑在插件层面做处理，但又考虑到通用性，所以还是发了一个通过 preventDefault 解决这个问题的  Debug 版本，感谢提问。
