### ISSUE TITLE
不能使用

### ISSUE THREAD

**Issue by lanqingqingwoqini** [BensonDu/vue-directive-touch#3]
Failed to resolve directive: tap

**Comment by BensonDu** [comment]
可否把使用方法贴出来 ？

**Comment by lanqingqingwoqini** [comment]
先下载 然后在main.js引入了那个初始化，就那2句话，然后在其他页面就直接类似这样的   在标签上<li v-touch:tap="oneReply（1）">一级回复</li> 是不是我传参数不对 还是除了在main.js初始化 其他页面也需要做点什么

**Comment by lanqingqingwoqini** [comment]
li标签上  v-touch:tap="oneReply（1）"

**Comment by BensonDu** [comment]
`<!DOCTYPE html>
<html lang=en>
<head>
    <meta charset=utf-8>
    <title>加载中...</title>
    <meta name=mobile-web-app-capable content=yes>
    <meta http-equiv=Cache-Control content="no-cache, no-store, must-revalidate">
    <meta http-equiv=Pragma content=no-cache>
    <meta http-equiv=Expires content=0>
    <script>!function (e) { var d = document.documentElement, b = window.devicePixelRatio, b = 3 <= b ? 3 : 2 <= b ? 2 : 1, a = 1 / b, c = document.querySelector('meta[name="viewport"]'), a = "initial-scale=" + a + ",maximum-scale=" + a + ",minimum-scale=" + a + ",user-scalable=no,width=device-width,viewport-fit=cover"; c ? c.setAttribute("content", a) : document.write('<meta name="viewport" content="' + a + '"/>'); c = function () { var a = d.clientWidth; d.style.fontSize = a / e * 100 + "px" }; c(); window.addEventListener("resize", c) }(750);</script>
</head>
<body>
    <div id="app">
        <p v-text="message"></p>
        <h3 v-touch:tap="call">点击</h3>
        <h3 v-touch:tap="param('123')">传参</h3>
    </div>
    
    <script src="https://unpkg.com/vue"></script>
    
    <script src="//awp-assets.meituan.net/hfe/fep/cb9e58e97b798ea85cb376bc3416b714.js"></script>
    <script>
        var app = new Vue({
            el: '#app',
            data: {
                message: 'Hello Vue touch'
            },
            methods:{
                call: function (index) {
                    console.log(index)
                },
                param: function (data) {
                    return function () {
                        console.log(data);
                    }
                }
            }
        })
    </script>
</body>
</html>`

**Comment by BensonDu** [comment]
查看这个使用 [Demo](http://i.meituan.com/awp/hfe/fep/c69e4f72449142bac31e82d8d0da5589.html)，查看页面源码。
核对下自己的使用方法。
