### ISSUE TITLE
请问怎么获取到滑动的距离？

### ISSUE THREAD

**Issue by WTFAYM** [BensonDu/vue-directive-touch#5]
如题：请问怎么样获取到滑动的距离，业务需求例如左滑水平方向上的移动距离，然后根据滑动的距离改变遮罩层的透明度，并根据滑动距离来判断是否隐藏滑动盒子。

**Comment by BensonDu** [comment]
参照文档 [传参](https://github.com/BensonDu/vue-directive-touch#%E4%BC%A0%E5%8F%82) ：可以获取到 event, start, end 三个对象，start 与 end 分别包含了起止的信息。

**Comment by sparGuan** [comment]
不传参就获取不了event,start,end三个参数啦
