### ISSUE TITLE
不循环就获取不了event，start，end这三个参数了？

### ISSUE THREAD

**Issue by sparGuan** [BensonDu/vue-directive-touch#6]
触摸事件放在父节点，没使用v-for，没法获取距离

**Comment by BensonDu** [comment]
代码片段可否贴下 ？

**Comment by sparGuan** [comment]
![0a0r efl3trc_yjieqx fv](https://user-images.githubusercontent.com/28480563/36884255-b4c97eea-1e1a-11e8-924c-6a5fa18ff725.png)

**Comment by BensonDu** [comment]
run(event, start, end){ }
直接拿参就可以了 ~

**Comment by sparGuan** [comment]
可以了，希望文档上加下哈~
