### ISSUE TITLE
你好，请问如何在同一个节点给tap事件绑定多个函数呢？

### ISSUE THREAD

**Issue by enkechan** [BensonDu/vue-directive-touch#8]
你好，请问如何在同一个节点给tap事件绑定多个函数呢？试过以下3种方式都不行。1.v-touch:tap='fn1(p)' v-touch:tap='fn2(p)'，2.v-touch:tap="fn1(p);fn2(p)"，3.v-touch:tap="fn1(p),fn2(p)"。都只能执行后绑定的函数，似乎发生了覆盖

**Comment by BensonDu** [comment]
仔细阅读文档，/* 自定义指令方法: 附带参数 */ 。文档有详细解释 ~
