### ISSUE TITLE
运行的时候 所有 事件 都会执行一遍

### ISSUE THREAD

**Issue by hstrawdog** [BensonDu/vue-directive-touch#9]
![image](https://user-images.githubusercontent.com/8399830/37944335-ae6ab4d2-31ad-11e8-8c4a-8bc39fb12cab.png)

**Comment by Kuro-P** [comment]
传参时，methods中的方法返回值得是一个函数_(´ཀ`」 ∠)_

**Comment by BensonDu** [comment]
仔细看下文档，https://github.com/BensonDu/vue-directive-touch#%E4%BC%A0%E5%8F%82
